module Problem2
(*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms
  By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.
*)

let fibonacci state = 
  let prev1, prev2 = state

  if prev2 < 4000000
  then Some(state, (prev2, prev1 + prev2))
  else None

let even v = v % 2 = 0

let fibbo = 
  Seq.unfold fibonacci (1, 2)
  |> Seq.map snd
  |> Seq.filter even
  |> Seq.sum